package stemmer

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestNewRussianStemmer(t *testing.T) {
	s := NewRussianStemmer()
	require.NotNil(t, s)
}

func TestRussianStemmer_IsStopWord(t *testing.T) {
	s := NewRussianStemmer()
	require.True(t, s.IsStopWord("и"))
	require.True(t, s.IsStopWord("И"))
	require.False(t, s.IsStopWord("яблоко"))
}

func TestRussianStemmer_Stem(t *testing.T) {
	s := NewRussianStemmer()
	t.Run("stop word", func(t *testing.T) {
		require.Equal(t, "и", s.Stem("и"))
		require.Equal(t, "и", s.Stem("И"))
	})

	f := func(word, stem string) {
		t.Helper()
		require.Equal(t, stem, s.Stem(word))
	}

	f("странствуя", "странству")
	f("маслом", "масл")
	f("поражал", "поража")
	f("тревожило", "тревож")
	f("судырь", "судыр")
	f("занять", "заня")
	f("покраснеете", "покраснеет")
	f("предприятием", "предприят")
	f("несмелые", "несмел")
	f("девицей", "девиц")
	f("занятые", "занят")
	f("гордостью", "гордост")
	f("простояла", "простоя")
	f("кофею", "коф")
	f("пелагея", "пелаге")
	f("нахальство", "нахальств")
	f("содрогнется", "содрогнет")
	f("провод", "провод")
	f("оградясь", "оград")
	f("пить", "пит")
	f("юридическом", "юридическ")
	f("нетерпелив", "нетерпел")
	f("немом", "нем")
	f("выгоняют", "выгоня")
	f("рассчитаны", "рассчита")
	f("спугнет", "спугнет")
	f("оледенило", "оледен")
	f("маловажной", "маловажн")
	f("зарю", "зар")
	f("боязливее", "боязлив")
	f("солнечного", "солнечн")
	f("подделывал", "подделыва")
	f("откровенный", "откровен")
	f("надворный", "надворн")
	f("январе", "январ")
	f("духоте", "духот")
	f("хватили", "хват")
	f("рысак", "рысак")
	f("недосягаемым", "недосяга")
	f("рассчитывая", "рассчитыв")
	f("нетерпение", "нетерпен")
	f("развившись", "разв")
	f("подружились", "подруж")
	f("подслуживается", "подслужива")
	f("мочи", "моч")
	f("подвел", "подвел")
	f("расселись", "рассел")
	f("ковша", "ковш")
	f("сойду", "сойд")
	f("дуни", "дун")
	f("став", "став")
	f("умен", "ум")
	f("чистом", "чист")
	f("утоли", "утол")
	f("навзничь", "навзнич")
	f("легкомысленно", "легкомыслен")
	f("полнейшего", "полн")
	f("простыню", "простын")
	f("сообщили", "сообщ")
	f("восьмом", "восьм")
	f("плач", "плач")
	f("оброка", "оброк")
	f("полупросыпаясь", "полупросып")
	f("ответил", "ответ")
	f("плетнем", "плетн")
	f("благодарна", "благодарн")
	f("вялыми", "вял")
	f("негодяй", "негодя")
	f("предисловие", "предислов")
	f("дворники", "дворник")
	f("приезжали", "приезжа")
	f("обвинить", "обвин")
	f("батальоны", "батальон")
	f("калека", "калек")
	f("обольстительнее", "обольстительн")
	f("коробочками", "коробочк")
	f("избаловали", "избалова")
	f("удалились", "удал")
	f("архитектура", "архитектур")
	f("барин", "барин")
	f("конторе", "контор")
	f("источнике", "источник")
	f("сумасбродом", "сумасброд")
	f("вырываются", "вырыва")
	f("помнить", "помн")
	f("ночуешь", "ночуеш")
	f("мольбами", "мольб")
	f("поставлен", "поставл")
	f("привстала", "привста")
	f("погрустив", "погруст")
	f("бесчестным", "бесчестн")
	f("погулять", "погуля")
	f("материнское", "материнск")
	f("клетку", "клетк")
	f("стал", "стал")
	f("келья", "кел")
	f("харькоеве", "харькоев")
	f("плечи", "плеч")
	f("том", "том")
	f("управления", "управлен")
	f("хриплым", "хрипл")
	f("привязанности", "привязан")
	f("михайловским", "михайловск")
	f("пересылались", "пересыла")
	f("галлы", "галл")
	f("именьишко", "именьишк")
	f("обовьют", "обовьют")
	f("упорная", "упорн")
	f("плелся", "плел")
	f("бешенстве", "бешенств")
	f("непроницаема", "непроницаем")
	f("туманных", "тума")
	f("заблистала", "заблиста")
	f("высшему", "высш")
	f("спора", "спор")
	f("подвернувшемуся", "подвернувш")
	f("кротким", "кротк")
	f("ногам", "ног")
	f("синеющих", "синеющ")
	f("батарею", "батар")
	f("понятен", "понят")
	f("фантазия", "фантаз")
	f("ножами", "нож")
	f("оборванной", "оборва")
	f("неуклюжий", "неуклюж")
	f("гадкий", "гадк")
	f("кушать", "куша")
	f("жирок", "жирок")
	f("предавать", "предава")
	f("вещим", "вещ")
	f("плыл", "плыл")
	f("добродетельного", "добродетельн")
	f("сонных", "сон")
	f("канал", "кана")
	f("тучами", "туч")
	f("деревню", "деревн")
	f("оборванец", "оборванец")
	f("хлада", "хлад")
	f("толстый", "толст")
	f("возни", "возн")
	f("обезображеннее", "обезображен")
	f("свертывают", "свертыва")
	f("мутно", "мутн")
	f("переговорено", "переговор")
	f("начну", "начн")
	f("суматохи", "суматох")
	f("рыдающие", "рыда")
	f("шлезвиг", "шлезвиг")
	f("нерв", "нерв")
	f("штопать", "штопа")
	f("оттенок", "оттенок")
	f("посолиднее", "посолидн")
	f("щегольской", "щегольск")
	f("поймет", "поймет")
	f("ширится", "шир")
	f("приискания", "приискан")
	f("слабость", "слабост")
	f("отпаривал", "отпарива")
	f("многими", "мног")
	f("артельщика", "артельщик")
	f("детьми", "детьм")
	f("понявший", "поня")
	f("нянечка", "нянечк")
	f("перелистывая", "перелистыв")
	f("расплывается", "расплыва")
	f("приглашает", "приглаша")
	f("смотрель", "смотрел")
	f("оспу", "осп")
	f("удостоверившись", "удостовер")
	f("кумиры", "кумир")
	f("конфузливы", "конфузлив")
	f("жилет", "жилет")
	f("умеют", "умеют")
	f("порфирий", "порфир")
	f("решаете", "реша")
	f("отмыли", "отм")
	f("противоречило", "противореч")
	f("ленивых", "ленив")
	f("огородишком", "огородишк")
	f("замерзнуть", "замерзнут")
	f("приходится", "приход")
	f("несчастный", "несчастн")
	f("исправления", "исправлен")
	f("высасывал", "высасыва")
	f("подстилая", "подстил")
	f("прекрасной", "прекрасн")
	f("расстроенный", "расстроен")
	f("подоконник", "подоконник")
	f("образованный", "образова")
	f("отжила", "отж")
	f("поесть", "поест")
	f("заслыша", "заслыш")
	f("прибавилось", "прибав")
	f("отправлении", "отправлен")
	f("завитые", "завит")
	f("недогадливый", "недогадлив")
	f("изуродованный", "изуродова")
	f("блаженство", "блаженств")
	f("охмелел", "охмелел")
	f("куртке", "куртк")
}

func TestCyrillicToRoman(t *testing.T) {
	f := func(cyrillic, roman string) {
		t.Helper()
		require.Equal(t, roman, cyrillicToRoman(cyrillic))
	}

	f("", "")
	f("и", "i")
	f("И", "i")
	f("быстрый", "bystryj")
	f("яблоко", "Abloko")
	f("Яблоко", "Abloko")
	f("Подъезд", "pod\"ezd")
	f("держаться", "derxat'sA")
	f("привет", "privet")
	f("щёлкать", "Welkat'")
	f("foo", "foo")
	f("s',", "s',")
}

func Test_romanToCyrillic(t *testing.T) {
	f := func(roman, cyrillic string) {
		t.Helper()
		require.Equal(t, cyrillic, romanToCyrillic(roman))
	}

	f("", "")
	f("i", "и")
	f("bystryj", "быстрый")
	f("Abloko", "яблоко")
	f("privet", "привет")
	f("pod\"ezd", "подъезд")
	f("derxat'sA", "держаться")
}

func TestRussianStemmer_regions(t *testing.T) {
	f := func(word, rv, r2 string) {
		t.Helper()
		s := NewRussianStemmer()
		nrv, nr2 := s.regions(word)
		require.Equal(t, rv, nrv)
		require.Equal(t, r2, nr2)
	}

	f("vesna", "sna", "")
	f("prygat'", "gat'", "'")
	f("knigu", "gu", "")
	f("igraet", "graet", "")
	f("solncem", "lncem", "")
	f("Hital", "tal", "")
	f("cvetka", "tka", "")
	f("dumaU", "maU", "")
	f("lUbov'U", "bov'U", "'U")
	f("hodili", "dili", "i")
	f("rabotaew'", "botaew'", "aew'")
	f("pesni", "sni", "")
	f("begut", "gut", "")
	f("vody", "dy", "")
	f("pisala", "sala", "a")
	f("uHiw'sA", "Hiw'sA", "'sA")
	f("osen'U", "sen'U", "'U")
	f("meHtaem", "Htaem", "")
	f("stolu", "lu", "")
	f("letali", "tali", "i")
	f("derevom", "revom", "om")
	f("gotovlU", "tovlU", "lU")
	f("kowek", "wek", "")
	f("spim", "m", "")
	f("oblaka", "blaka", "a")
	f("smotrel", "trel", "")
	f("list'ev", "st'ev", "")
	f("risuem", "suem", "")
	f("plavali", "vali", "i")
	f("gorode", "rode", "e")
	f("beseduU", "seduU", "uU")
	f("mawinami", "winami", "ami")
	f("Hitaew'", "taew'", "'")
	f("tvoril", "ril", "")
	f("edoj", "doj", "")
	f("pryxke", "xke", "")
	f("sidim", "dim", "")
	f("gorelo", "relo", "o")
	f("pomniw'", "mniw'", "'")
	f("lesom", "som", "")
	f("idut", "dut", "")
	f("govoril", "voril", "il")
	f("sHast'em", "st'em", "")
	f("begaew'", "gaew'", "'")
	f("znal", "l", "")
	f("uHilis'", "Hilis'", "is'")
	f("rybami", "bami", "i")
	f("vidim", "dim", "")
	f("leto", "to", "")
	f("samosoverwenstvovanie", "mosoverwenstvovanie", "overwenstvovanie")
	f("vysokointellektual'nyj", "sokointellektual'nyj", "ointellektual'nyj")
	f("obWepriznannyj", "bWepriznannyj", "riznannyj")
	f("nepredskazuemost'", "predskazuemost'", "skazuemost'")
	f("poluprovodnikovyj", "luprovodnikovyj", "rovodnikovyj")
	f("al'ternativnost'", "l'ternativnost'", "nativnost'")
	f("mnogoobeWaUWij", "goobeWaUWij", "eWaUWij")
	f("izobrazitel'noe", "zobrazitel'noe", "razitel'noe")
	f("aglomeracionnyj", "glomeracionnyj", "eracionnyj")
	f("vysokokvalificirovannyj", "sokokvalificirovannyj", "okvalificirovannyj")
	f("perpendikulArnyj", "rpendikulArnyj", "dikulArnyj")
	f("Emocional'nost'", "mocional'nost'", "ional'nost'")
	f("organizovannost'", "rganizovannost'", "izovannost'")
	f("predprinimatel'stvo", "dprinimatel'stvo", "imatel'stvo")
	f("konstruktivnost'", "nstruktivnost'", "tivnost'")
	f("gipotetiHeskij", "potetiHeskij", "etiHeskij")
	f("sel'skohozAjstvennyj", "l'skohozAjstvennyj", "ozAjstvennyj")
	f("mnogoznaHitel'nyj", "goznaHitel'nyj", "naHitel'nyj")
	f("giperinflAciA", "perinflAciA", "inflAciA")
	f("materializovat'sA", "terializovat'sA", "ializovat'sA")
	f("razvlekatel'nyj", "zvlekatel'nyj", "atel'nyj")
	f("programmirovanie", "grammirovanie", "mirovanie")
	f("mnogoslojnost'", "goslojnost'", "lojnost'")
	f("Eksperimental'nyj", "ksperimental'nyj", "imental'nyj")
	f("informacionnyj", "nformacionnyj", "macionnyj")
	f("EkologiHeski", "kologiHeski", "ogiHeski")
	f("protivopoloxnost'", "tivopoloxnost'", "opoloxnost'")
	f("strukturirovannyj", "kturirovannyj", "irovannyj")
	f("protivodejstvie", "tivodejstvie", "odejstvie")
	f("Elektrooborudovanie", "lektrooborudovanie", "trooborudovanie")
}
